#!/bin/sh

WCFLAGS="-I/usr/local/include "
WLFLAGS="-L/usr/local/lib "
WLIBS="-lwraster -lXpm -lpng -ljpeg -lXext -lXext -lX11  -lm"

usage="Usage: get-wraster-flags [--cflags] [--ldflags] [--libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case $1 in
    --cflags)
	echo $WCFLAGS
        ;;
    --ldflags|--lflags)
	echo $WLFLAGS
        ;;
    --libs)
	echo $WLIBS
        ;;
    *)
	echo "${usage}" 1>&2
	exit 1
	;;
  esac
  shift
done
