.TH "Workspace" 8 "March 2001" "Debian Project"
.SH NAME
upgrade-workspace-defaults \- Convert old workspace configuration files
.SH SYNOPSIS
.B upgrade-workspace-defaults
.SH DESCRIPTION
Some old versions of Workspace used different names or different syntax
for some configuration options, which in turn used to cause some newer
versions of Workspace not to start up correctly.  Nowadays this is no
longer a problem but this utility is provided to support upgrades from these
old versions of Workspace.
.SH SEE ALSO
The Workspace User Guide
.PP
The Workspace FAQ
.PP
The Workspace changelog and NEWS files (in /usr/share/doc/workspace)
.PP
.BR workspace (1x)
.SH AUTHOR
This utility and manpage were written by Marcelo E. Magallon,
<mmagallo@debian.org>, for the Debian Project.  It might be used freely by
others.
